name: Build Dungeon with Pygbag
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Greg Games - Dungeon
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pygbag
      run: |
        echo "Installing pygbag 0.9.3"
        python -m pip install --upgrade pip
        python -m pip install pygbag==0.9.3

    - name: Build the game
      run: |
        echo "Building the game with pygbag"
        python -m pygbag --build --ume_block=0 --title "Greg ganes - Dungeon" dungeon/main.py

    - name: Upload to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dungeon/build/web
